# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: Use Node 12 or higher
  inputs:
    versionSpec: '=12.0.0'
# - task: APIContractSecurityAudit@4
#  inputs:
#    apiToken: '$(API_KEY)'
#    platformUrl: 'https://demolabs.42crunch.cloud'
#   defaultCollectionName: 'Demo APIs v1'
#    logLevel: 'DEBUG'
- task: APIContractSecurityAudit@5
  inputs:
   platformServiceConnection: '42Crunch Platform Connection'
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    python -m pip install --upgrade pip
    python -m pip install requests
  displayName: 'Install dependencies'

- script: |
    python scripts/conformance_scan_v2.py --action create_conf --credentials $(API_KEY) --api_uuid $(API_UUID)
  displayName: 'Run Scan Configuration Script'