# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  platformUrl: 'https://demolabs.42crunch.cloud'
  PIXI_host: "https://photo-demo.westeurope.cloudapp.azure.com/ali/api"

steps:
- task: NodeTool@0
  displayName: Use Node 12 or higher
  inputs:
    versionSpec: '=12.0.0'
# - task: APIContractSecurityAudit@4
#  inputs:
#    apiToken: '$(API_KEY)'
#    platformUrl: 'https://demolabs.42crunch.cloud'
#   defaultCollectionName: 'Demo APIs v1'
#    logLevel: 'DEBUG'
- task: APIContractSecurityAudit@5
  inputs:
     platformServiceConnection: '42Crunch Platform Connection'
     apiToken: '$(42C_API_TOKEN)'
     minScore: '75'
     platformUrl: '$(platformUrl)'
     logLevel: DEBUG
     defaultCollectionName: 'AzureDevOps Github Pixi main'
     ignoreFailures: 'false'
     jsonReport: 'audit-action-report-$(Build.BuildId).json'
     sarifReport: 'audit-report-$(Build.BuildId).sarif'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

# Required: Fetch Pixi API UUID from the Audit summary report
- task: CmdLine@2
  displayName: 'Check Audit Summary Report'
  inputs:
    script: |
      echo "Audit JSON Report:"
      cat $(Build.Repository.LocalPath)/audit-action-report-$(Build.BuildId).json

      apiId=$(cat $(Build.Repository.LocalPath)/audit-action-report-$(Build.BuildId).json | jq -r '.audit.report."OASFiles/Pixi\ App\ Good\ Scan.json".apiId')
      
      printf "\n"
      echo "Pixi API UUID: $apiId"
      echo "##vso[task.setvariable variable=API_UUID]$apiId"

# Required: Fetch Pixi API AliasId from the .42c/conf.yaml
- script: |
    python -m pip install --upgrade pip
    python -m pip install yq
  displayName: 'Install yq'
- script: python -m pip install requests --upgrade pip
  displayName: 'Install tools'

- task: CmdLine@2
  displayName: 'Fetch API AliasId'
  inputs:
    script: |
      echo "Audit JSON Report:"
      cat $(Build.Repository.LocalPath)/.42c/conf.yaml

      aliasId=$(cat $(Build.Repository.LocalPath)/.42c/conf.yaml | yq '.apis."OASFiles/Pixi\ App\ Good\ Scan.json".alias')

      printf "\n"
      echo "Pixi API AliasId: $aliasId"
      echo "##vso[task.setvariable variable=API_ALIAS_ID]$aliasId"
#- script: |
#    python -m pip install --upgrade pip
#    python -m pip install requests
#  displayName: 'Install dependencies'

#- script: |
#   python scripts/conformance_scan_v2.py --action create_conf --credentials $(API_KEY) --api_uuid $(API_UUID)
#  displayName: 'Run Scan Configuration Script'