apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pixidb
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pixidb
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pixidb
{{ include "42c-pixiapi.labels" . | indent 8 }}

    spec:
      containers:
      - name: {{ .Release.Name }}-pixidb
        image: {{ .Values.pixidb.repository }}:{{ .Values.pixidb.version }}
        imagePullPolicy: {{ .Values.pixidb.pullPolicy | quote }}
        ports:
          - containerPort: {{ .Values.pixidb.listen_port | default 27017 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pixi
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pixiapp
  replicas: {{ .Values.pixiapp.replicas }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pixiapp
{{ include "42c-pixiapi.labels" . | indent 8 }}
{{ if .Values.pixiapp.inject_firewall }}
        firewall-injection: enabled
      annotations:
        xliic.com/http-only: "enabled"
        xliic.com/container-port: "8080"
        xliic.com/protection-token: "apifirewall-protection-token"
        xliic.com/configmap-ref: "apifirewall-props"
        xliic.com/tls-secret-name: "apifirewall-tls"
        xliic.com/jwk-secret-key: "pixirsa.jwk"
        xliic.com/jwt-validation: "enabled"
        xliic.com/platform-url: "protection.demolabs.42crunch.cloud:8001"
        xliic.com/external-logging: "disabled"
        xliic.com/logs-pvc-name: "apifirewall-logs"
{{end}}        
    spec:
      containers:
      - name: {{ .Release.Name }}-pixiapp
        image: {{ .Values.pixiapp.repository }}:{{ .Values.pixiapp.version }}
        imagePullPolicy: {{ .Values.pixiapp.pullPolicy | quote }}
        ports:
          - containerPort: {{ .Values.pixiapp.listen_port | default 8090 }}
